### ISSUE TITLE
Addon ruining my custom CSS for unloaded tabs. The text field for it seems uneditable.

### ISSUE THREAD

**Issue by mzso** [Lej77/tab-unloader-for-tree-style-tab#25]
Hi!
The very first thing I noticed when installing this addon is my custom CSS being overridden.
I would have liked to comment out this addon's CSS in its textfield but it's not editable.
Funnily, I also had decreased opacity, but to 0.35.
I even have to restart the browser after I disable this addon, to get the TST CSS working again.

**Comment by Lej77** [comment]
Ahh, that is some unfortunate design from my part, thanks for reporting it! So first you can indeed disable the custom style changes via the `Dim unloaded tabs in Tree Style Tab's sidebar` setting located in the `Other Settings` section. The reason it wasn't placed in the `Custom Tree Style Tab Style` section was that this section was added later and the old setting just remained where it was which does make it a bit difficult to find. I will move that setting into the `Custom Tree Style Tab Style` section to avoid that for future users.

The other issue that disabling the extension didn't disable the styling occurred since that wasn't possible when I made this extension and is actually the reason for the `Disable extension` button at the top of the options page, using that would have removed the custom styling without restarting Firefox or Tree Style Tab. Anyway Tree Style Tab added a [new event to its API (the `wait-for-shutdown` event)](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#unregister-from-tst) which is available since Tree Style Tab v3.1.2. So I will add support for that too so that at least this problem won't occur for users again.

**Comment by Lej77** [comment]
I released version 6.2 of this extension which included the changes I just mentioned.

**Comment by mzso** [comment]
Cool. All good now.
