### ISSUE TITLE
Suggestions/requests for clearer wording

### ISSUE THREAD

**Issue by digital-carver** [Lej77/tab-unloader-for-tree-style-tab#36]
First of all, thank you very much for the detailed options page and the informative descriptions there. It's very useful to be able to customize the behaviour exactly the way we want, and the descriptions make it immediately clear how the various interactions work. 

This issue is for the few places where I think it can be improved a bit:

* The main description of the addon (in the addons page) lists the context menu items that can be added, and gives their names as "Unload Tab", "Unload Tree", etc. The actual name used in the context menu is "Suspend Tab(s)" , "Suspend Tree", etc. I was confused by this at first, thinking maybe I had another addon that was doing this. Could you change these to be consistent with each other? 

* In the options page:  
  - Under "Wait for long press", there's "If checked, then cancel if an event is registered; otherwise, only allow if an event is registered." Could you add a short description of what counts as an "event"? 
  - In the final "Other settings", the first option is to "use the unload method again" after a short delay. It's not clear why and when this might be necessary though. Is it for some older version of Firefox that wouldn't always unload the tabs properly, or is there a bug in some OS, or is it something else? A mention of why we might want this would be good.

**Comment by Lej77** [comment]
Thank you for the feedback! I have just released version 6.13 of the extension which has a number of improvements to the options page. I think I addressed all of your concerns:

- I changed the default label to say `Unload` instead of `Suspend` since that is the terminology I use elsewhere in the extension.
- I added more info and tried to clarify how the "Wait for long press" condition works.
- I moved the "use the unload method again" option to the `Fix for failed tab restore` section where it belongs. (It was added before that section existed and tried to address the same problem.) I also added a link to the issue that caused the option to be added to further clarify what its use was.

I also split the option page sections into categories to make it easier to get an overview of what can be done with the extension which is something I have felt was needed for a while now. So overall I am quite happy with these improvements!
