### ISSUE TITLE
[Enhancement] Unload Tree - Setting to ignore currently selected tab

### ISSUE THREAD

**Issue by thefinalwolf** [Lej77/tab-unloader-for-tree-style-tab#38]
Thanks for the useful tweaks to Tree Style Tab.

I was curious if an option to ignore the currently selected tab could be added for the **Unload Tree** feature. It would be useful for those times where you middle-click a ton of links that open under the current tree, but you want them unloaded without interrupting the current page. 

I've attached an example.

![image](https://user-images.githubusercontent.com/9045213/162325245-e6e1813f-c6af-42dc-b043-118b52c088e0.png)

**Comment by Lej77** [comment]
I have just release version 6.14 of this extension and it includes some new options that should allow for the behavior that you describe. You can for example enable the new `Unload descendants` context menu item and use that instead of the `Unload tree` context menu item to not unload the root tab of the tree you clicked on.
