### ISSUE TITLE
[Help/Support] Show hidden tabs in Tree Style Tab's Sidebar no longer working.

### ISSUE THREAD

**Issue by lucasama** [Lej77/tab-unloader-for-tree-style-tab#45]
The option to "Show hidden tabs in Tree Style Tab's Sidebar" is no longer working for me.

If I use the option to "Hide unloaded tabs with the tab hiding API" then I cannot see all the unloaded/hidden tabs in the Tree Style Tab's Sidebar. Not sure if something changed or some other addon messed with my configuration.

**Comment by Lej77** [comment]
Tree Style Tab seems to have changed how it handles `hidden` tabs. Previously it used CSS to hide them (which this extension could override) but now it seems to remove them from the DOM completely which probably makes these feature impossible to implement. 

From what I know Tree Style Tab's policy is to mirror Firefox's behavior and since showing hidden tabs isn't possible in Firefox's native tab bar it likely won't become an option for TST's sidebar either.

**Comment by lucasama** [comment]
@Lej77 This is now fixed with the latest version of TST :-)
https://github.com/piroor/treestyletab/issues/3495

**Comment by Lej77** [comment]
Okay, so now TST has a hidden option called `renderHiddenTabs` that allows showing hidden tabs in the sidebar. I should probably update the option page with this information.
